# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-02 22:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name=b'\xd7\xa9\xd7\x9d')),
                ('_class', models.CharField(max_length=100, verbose_name=b'\xd7\xa9\xd7\x99\xd7\x99\xd7\x9b\xd7\x95\xd7\xaa')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name=b'\xd7\xaa\xd7\x99\xd7\x90\xd7\x95\xd7\xa8')),
            ],
        ),
        migrations.CreateModel(
            name='Excluded_Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=30, verbose_name=b'\xd7\xa4\xd7\xa2\xd7\x95\xd7\x9c\xd7\x94')),
            ],
        ),
        migrations.CreateModel(
            name='Excluded_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='balance_app.Excluded_Action')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='balance_app.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name=b'\xd7\xa9\xd7\x9d')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name=b'\xd7\xaa\xd7\x90\xd7\xa8\xd7\x99\xd7\x9a \xd7\xa4\xd7\xa2\xd7\x95\xd7\x9c\xd7\x94')),
                ('reference', models.CharField(db_index=True, max_length=40, verbose_name=b'\xd7\x90\xd7\xa1\xd7\x9e\xd7\x9b\xd7\xaa\xd7\x90')),
                ('description', models.CharField(db_index=True, max_length=100, verbose_name=b'\xd7\xaa\xd7\x90\xd7\x95\xd7\xa8')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name=b'\xd7\xa1\xd7\x9b\xd7\x95\xd7\x9d')),
                ('comment', models.TextField(blank=True, verbose_name=b'\xd7\x94\xd7\xa2\xd7\xa8\xd7\x95\xd7\xaa')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='balance_app.Account')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='balance_app.Owner')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction_to_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, verbose_name=b'\xd7\x94\xd7\xa2\xd7\xa8\xd7\x95\xd7\xaa')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='balance_app.Category', verbose_name=b'\xd7\xa7\xd7\x98\xd7\x92\xd7\x95\xd7\xa8\xd7\x99\xd7\x94')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='balance_app.Transaction', verbose_name=b'\xd7\xa4\xd7\xa2\xd7\x95\xd7\x9c\xd7\x94')),
            ],
        ),
        migrations.CreateModel(
            name='Word_to_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(db_index=True, max_length=100, verbose_name=b'\xd7\xaa\xd7\x99\xd7\x90\xd7\x95\xd7\xa8')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='balance_app.Category')),
            ],
        ),
    ]
