# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-04 07:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('balance_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='charge_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name=b'\xd7\xaa\xd7\x90\xd7\xa8\xd7\x99\xd7\x9a \xd7\x97\xd7\x99\xd7\x95\xd7\x91'),
            preserve_default=False,
        ),
    ]
