# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-07 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance_app', '0002_transaction_charge_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='dirty',
            field=models.BooleanField(default=True),
        ),
    ]
