# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance_app', '0003_transaction_dirty'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='_id',
            field=models.IntegerField(null=True),
        ),
    ]
